---
title: "CPS Data Summary"
author: "Rachel Lane"
date: "`r format(Sys.Date(), format = '%B %d, %Y')`"
params:
  parent_dir: "a12_cps_data" # relative to project root
  version: "2026-03-04" 
  raw_data_cps:
    value:
      file: "UIC Asthma Status Data Albuterol SoW Shell_07252025.xlsx"
      sheet: "SY22, 23, 24 and 25 Asthma Stat"
      box_id: '1938297974039'
      clean_name: "student_counts"
  raw_data_schools_metadata:
    value: 
      file: "CPS Schools CCAs Regions.xlsx"
      sheet: NULL
      box_id: '2071252778107'
      clean_name: "schools"
  raw_data_utilization:
    value:
      file: "CPS 2023-2025 utilization recode.xlsx"
      sheet: "Sheet1"
      box_id: '2017350498669'
      clean_name: "inhaler_events"
  raw_data_waves: # added 2026-01-21
    value:
      file: "CPS Ramp Up School List_MostUpdated.xlsx"
      sheet: "Sheet1"
      box_id: "2109640911794"
      clean_name: "waves"
  raw_sy_dates: # added 2026-03-04
    value:
      box_id: "2154041346707"
      file: "schoolyear_dates.xlsx"
      sheet: "Sheet1"
      clean_name: "school_year_dates"
      force_preproc: true
  enrollment_count_files: # box ids
    value: 
      sy_22: "2154049626576"
      sy_23: "2154041838698"
      sy_24: "2154043506963"
      sy_25: "2154043912572"
      sy_26: "2154047037077"
  force_preproc: FALSE
knit: |
  (function(input, ...) {
      rmarkdown::render(
        input, 
        output_format = rmarkdown::word_document(), 
        output_file   = paste0("33753_cps_data_", Sys.Date(), ".docx"),
        output_dir    = file.path(dirname(input), "output"),
        envir         = globalenv()
      )
  })
---




```{r chunk_opts, echo = FALSE, include = FALSE}
# define document options
knitr::opts_chunk$set(
  echo    = FALSE, eval    = TRUE, 
  message = FALSE, warning = FALSE
  )
```

```{r, include = FALSE}
# load libraries
library(tidyverse)
```

```{r chunk_opts, echo = FALSE, include = FALSE}
# define formatting options
options(knitr.kable.NA = '')
thm <- theme_set(theme_bw())
```

```{r}
# function for easier navigation of relative refs
nested_here <- function(
    ...,    
    parent_dir = params$parent_dir, 
    version    = params$version
    ) {
    here::here(parent_dir, version, ...)
}
```

```{r}
# (maybe) create subdirectories for code, data, output
walk(
    nested_here(c("R", "data", "output")),
    ~{if(!dir.exists(.x)) {dir.create(.x, recursive = TRUE)}}
    )
```


# Data Processing

## Align Raw Data Files

```{r}
# load preproc functions
source(nested_here("R", "r01_preproc.R"))

# raw data sources that need to be processed
raw_files <- params |> 
  keep_at(~ grepl("raw", .x)) 
names(raw_files) <- transpose(raw_files) |> 
    pluck("clean_name")
```

```{r}
# make school name/id crosswalk (multiple source files)
if(!file.exists(nested_here("data", "pre_school_ids.rds")) | params$force_preproc) {
  params$enrollment_count_files |> 
    imap(~{
      list(
        box_id     = .x, 
        sheet      = 1, 
        clean_name = gsub("sy", "school_enrollment", .y)
        )
      }) |> 
    map_dfr(fetch_and_preproc) |> 
    write_rds(nested_here("data", "pre_school_ids.rds"))
}
```

```{r, include = FALSE}
# for each raw file...
raw_files |> 
  iwalk(~{
    f_name         <- nested_here("data", paste0("pre_", .y, ".rds"))
    force_preproc  <- coalesce(.x |> pluck("force_preproc"), params$force_preproc)
    
    # if it doesn't exist or needs forced regeneration...
    if(!file.exists(f_name) | force_preproc) {
      
      # process and write to file
      fetch_and_preproc(.x) |> 
        write_rds(f_name)
      }
    })
```

## Merge 

```{r}
# make df with all combinations of school ids and years
merge(
  read_rds(nested_here("data", "pre_school_ids.rds")) |> 
    distinct(school_id),

  read_rds(nested_here("data", "pre_school_year_dates.rds")) |> 
    distinct(data_schoolyear) |> 
    filter(!grepl("[a-z]", data_schoolyear)),
  
  by = NULL
  ) |> 
  
  write_rds(nested_here("data", "mrg_school_ids_schoolyears.rds"))
```

```{r}
# (maybe) add school and date ids to inhaler events and write to file

# if( !file.exists(nested_here("data", "mrg_inhaler_events.rds")) | 
    # params$force_preproc ) {
  
  add_school_ids(
    read_rds(nested_here("data", "pre_inhaler_events.rds")),
    id_map = read_rds(nested_here("data", "pre_school_ids.rds"))
    ) |> 
    mutate(
      data_season = classify_dates(
        admin_date,
        syd_df = read_rds(nested_here("data", "pre_school_year_dates.rds"))
        )
    ) |> 
    left_join(
      read_rds(nested_here("data", "pre_school_year_dates.rds")) |> 
        select(where(is.factor)),
      by = c("data_season")
      ) |> 
    structure(unit = "event", timescale = "date") |> 
    droplevels() |> 
    write_rds(nested_here("data", "mrg_inhaler_events.rds"))
# }
```


```{r}
# (maybe) merge school and wave data and write to file

# if( !file.exists(nested_here("data", "mrg_school_chars.rds")) | 
    # params$force_preproc ) {
  
  full_join(
    read_rds(nested_here("data", "pre_schools.rds")),
    read_rds(nested_here("data", "pre_waves.rds")),
    by = "school_id"
    ) |> 
    
    mutate(
      wave = fct_na_value_to_level(wave, "Fall 2024"),
      impl_date      = as.Date(
        fct_recode(
          wave,
          "2023-09-01" = "Pilot",
          "2024-02-01" = "Feb 2024",
          "2024-04-01" = "April 2024",
          "2024-09-01" = "Fall 2024"
          )
        ),
      impl_schoolyear = fct_collapse(
        wave,
        "2023-2024" = c("Pilot", "Feb 2024", "April 2024"),
        "2024-2025" = c("Fall 2024")
        )
      ) |>
    structure(unit = "school", timescale = "invariant") |> 
    write_rds(nested_here("data", "mrg_school_chars.rds"))
  # }
```


```{r}
# (maybe) add school ids to student counts and write to file

# if( !file.exists(nested_here("data", "mrg_student_counts.rds")) | 
    # params$force_preproc ) {
    
  add_school_ids(
    read_rds(nested_here("data", "pre_student_counts.rds")),
    id_map = read_rds(nested_here("data", "pre_school_ids.rds"))
    ) |> 
    structure(unit = "student group", timescale = "schoolyear") |> 
    write_rds(nested_here("data", "mrg_student_counts.rds"))
# }
```

## Tabulate/Summarize

```{r}
# tabulate events by school and schoolyear

full_join(
  
  # all school_ids and data_schoolyears
  read_rds(nested_here("data", "mrg_school_ids_schoolyears.rds")),  
  
  # inhaler events by school_ids and data_schoolyear
  read_rds(nested_here("data", "mrg_inhaler_events.rds")),
  by      = c("school_id", "data_schoolyear")
  ) |> 
  summarise(
    n_events = sum(!is.na(row_id)),
    .by      = c(school_id, data_schoolyear)
    ) |> 
  
  # calculate cumulative counts
  arrange(school_id, data_schoolyear) |> 
  mutate(
    n_events_cumulative = cumsum(n_events),
    
    any_events = factor(
      n_events >= 1, 
      levels = c(FALSE, TRUE), 
      labels = c("No Events", "1+ Events")
      ),
    any_events_cumulative = factor(
      n_events_cumulative >= 1, 
      levels = c(FALSE, TRUE), 
      labels = c("No Events", "1+ Events")
      ),
    .by                 = school_id
    ) |>
  structure(unit = "school", timescale = "schoolyear") |> 
  write_rds(nested_here("data", "mrg_school_lvl_event_counts.rds"))
```


```{r}
# should be equivalent:
read_rds(nested_here("data", "mrg_inhaler_events.rds")) |> 
  count(data_schoolyear)

read_rds(nested_here("data", "mrg_school_lvl_event_counts.rds")) |> 
  summarise(n = sum(n_events), .by = data_schoolyear)
```

```{r}
# summarize all student counts at the school and school-year level

list(
  tabulate_fct(
    x_fct  = "student_race", 
    df     = read_rds(nested_here("data", "mrg_student_counts.rds"))
    ),
  
  tabulate_fct(
    x_fct  = "student_gender", 
    df     = read_rds(nested_here("data", "mrg_student_counts.rds"))
    ),
  
  read_rds(nested_here("data", "mrg_student_counts.rds")) |> 
    summarise(
      average_attendance = weighted.mean(average_attendance, student_count),
      across(c(
        "student_count",
        matches("_yes$"), 
        matches("_no$"),
        "student_days_present",
        "student_days_absent"
        ), ~ sum(.x, na.rm = TRUE)),
      .by = c(school_id, data_schoolyear)
      ) |> 
    mutate(across(
      ends_with("yes"), 
      list(pct = ~ (.x / student_count)*100),
      .names = "pct_{gsub('_count', '',  .col)}"
      ),
      .by = c(school_id, data_schoolyear)
      )
  ) |> 
  
  reduce(full_join, by = c("school_id", "data_schoolyear")) |> 
  structure(unit = "school", timescale = "schoolyear") |> 
  write_rds(nested_here("data", "mrg_school_lvl_student_counts.rds"))
```


```{r}
# merge all school-level annual data
full_join(
  read_rds(nested_here("data", "mrg_school_lvl_student_counts.rds")),
  read_rds(nested_here("data", "mrg_school_lvl_event_counts.rds")),
  by = c("school_id", "data_schoolyear")
  ) |> 
  filter(
    sum(n_events) > 0 | sum(!is.na(student_count)) > 0, 
    .by = c("school_id", "data_schoolyear")
    ) |> 
  droplevels() |> 
  
  # add school chars
  left_join(
    read_rds(nested_here("data", "mrg_school_chars.rds")),
    by = "school_id"
    ) |>
  relocate(names(read_rds(nested_here("data", "mrg_school_chars.rds")))) |> 
  arrange(data_schoolyear, school_id) |> 
  structure(unit = "school", timescale = "schoolyear") |> 
  write_rds(nested_here("data", "analytic_school_lvl.rds"))
```


```{r}
# check: schools with cps data per year
read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
  mutate(cps_data = !is.na(student_count)) |> 
  select(data_schoolyear, cps_data) |> 
  table()

# check: inhaler events by year
read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
  summarise(sum(n_events), .by = data_schoolyear)
```

# Describe School Chars by Year

```{r}
school_tby <- function(
    y_var,
    df,
    x_var = c(
      "notest(n_schools)", "grade_level", "notest(region)", "region_3grp", "region_2grp", 
      "student_count", "average_attendance", 
      "pct_student_race_american_indian", "pct_student_race_asian_hawaiian_pacific_islander",
      "pct_student_race_black_non_hispanic", "pct_student_race_hispanic", "pct_student_race_multi",
      "pct_student_race_unknown", "pct_student_race_white_non_hispanic",
      "notest(pct_student_race_middle_eastern_or_north_african)", 
      "pct_student_gender_female", "pct_student_gender_male", 
      "pct_student_gender_non_binary", "pct_student_gender_unknown", 
      "pct_asthma_yes", "pct_food_allergy_yes", "pct_non_food_allergy_yes", 
      "pct_student_504_yes", "pct_iep_yes", "pct_esl_yes", 
      "pct_frm_yes", "pct_homelessness_yes", 
      "n_events", "n_events_cumulative"
      ),
    tby_ctrl = arsenal::tableby.control(
      test           = FALSE,
      digits.n	      = NA,
      numeric.stats  = c("medianrange", "q1q3",  "meansd")
    ),
    labels = NULL
    ) {
  
  arsenal::tableby(
    formula = arsenal::formulize(y_var, x_var),
    data    = df,
    subset  = (!is.na(df$student_count)),
    strata  = data_schoolyear,
    control = tby_ctrl
    ) |> 
    arsenal:::summary.tableby(text = TRUE, labelTranslations = labels) |> 
    as.data.frame()
}
```

```{r}
write_table <- function(x, loc = nested_here("output", "tables")) {
  n_extant <- length(list.files(loc, "^t.*rds$"))
  write_rds(
    x,
    file.path(loc, glue::glue("t{sprintf('%03d', n_extant+1)}.rds"))
  )
}

# schools by wave, stratified by year
school_tby(
  y_var = "wave",
  df    = read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
    mutate(n_schools = "total")
  ) |> 
  
  structure(
    title = "School Characteristics by Implementation Wave",
    description = "Summary statistics of school-level characteristics and demographics. Schools are grouped by implementation wave (Pilot, Feb 2024, April 2024, Fall 2024) and overall. Data from each school year are tabulated separately (2021-2022 to 2024-2025)."
    )
  
  write_rds(nested_here("output", "tby_school_chars_by_wave.rds"))
```

```{r}
# schools by implementation wave, stratified by year
school_tby(
  y_var = "impl_schoolyear",
  df    = read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
    mutate(
      n_schools       = "total", 
      impl_schoolyear = fct_recode(
        impl_schoolyear, 
        "Impl. Group 1 (started in 2023-2024)" = "2023-2024",
        "Impl. Group 2 (started in 2024-2025)" = "2024-2025"
        )
      ),
  labels = list(data_schoolyear = "Data Describes Schools in Schoolyear...")
  ) |> 
  write_rds(nested_here("output", "tby_school_chars_by_impl_year.rds"))
```


```{r}
# any events
school_tby(
  y_var = "any_events",
  df    = read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
    mutate(n_schools       = "total") |> 
    filter(sum(n_events) > 0, .by = data_schoolyear) |> 
    droplevels(),
  labels = list(data_schoolyear = "Data Describes Schools in Schoolyear...")
  )
```

```{r}
# any events, 2023-2024 only, separating late implementers
school_tby(
  y_var = "any_events_l3",
  df    = read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
    mutate(n_schools       = "total",
           any_events_l3 = case_when(
             impl_schoolyear == "2023-2024" ~ "N/A (Impl Group 2)",
             n_events == 0 ~ "0 Events (Impl Group 1)",
             n_events > 0 ~ "1+ Events (Impl Group 1)"
             )
           ) |> 
    filter(data_schoolyear == "2023-2024") |> 
    droplevels(),
  labels = list(data_schoolyear = "Data Describes Schools in Schoolyear...")
  )
```



```{r}
# any events cumulative
school_tby(
  y_var = "any_events_cumulative",
  df    = read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
    mutate(n_schools       = "total") |> 
    filter(sum(n_events) > 0, .by = data_schoolyear) |> 
    droplevels(),
  labels = list(data_schoolyear = "Data Describes Schools in Schoolyear...")
  )
```


```{r}
# schools by inhaler uses, stratified by year
read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
  filter(!is.na(student_count)) |> 
  filter(sum(n_events) > 0, .by = data_schoolyear) |> 
  droplevels() |> 
  mutate(events_l3 = fct_cross(any_events, impl_schoolyear)) |> 
  select(data_schoolyear, events_l3) |> 
  table()
```

Events reported in 2023-2024, implemented in 2024-2025:

```{r}
read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
  filter(n_events > 0, data_schoolyear == "2023-2024", impl_schoolyear == "2024-2025") |> 
  left_join(
    
    read_rds(nested_here("data", "pre_school_ids.rds")),
    by = c("school_id", "data_schoolyear")
  ) |> 
  relocate(matches("name"))
```







Compare different groups of schools in baseline year

```{r}
rename_yes_no <- function(y, df) {
  df[["yes"]] <- df[[y]]
  df[["no"]] <- df[["student_count"]] - df[["yes"]]
  df |> 
    filter(!is.na(student_count)) |> 
    droplevels()
  }

binom_mods <- c("count_student_race_american_indian",
  "count_student_race_asian_hawaiian_pacific_islander",
  "count_student_race_black_non_hispanic",
  "count_student_race_hispanic",
  "count_student_race_multi",
  "count_student_race_unknown",
  "count_student_race_white_non_hispanic",
  "count_student_race_middle_eastern_or_north_african",
  "count_student_gender_female",
  "count_student_gender_male",
  "count_student_gender_non_binary",
  "count_student_gender_unknown",
  "student_count",
  "asthma_count_yes",
  "food_allergy_count_yes",
  "non_food_allergy_count_yes",
  "student_504_count_yes",
  "iep_count_yes",
  "esl_count_yes",
  "frm_count_yes",
  "homelessness_count_yes") |> 
  set_names() |> 
  map(~{
    eval(bquote(
      geepack::geeglm(
        cbind(yes, no) ~ data_schoolyear,
        data = rename_yes_no(
          .(.x),
          read_rds(nested_here("data", "analytic_school_lvl.rds"))
          ),
        family = binomial(link = "logit"),
        id     = school_id,
        waves  = data_schoolyear
        )
      ))
    })
```

```{r}
binom_mods$attendance <- geepack::geeglm(
   cbind(round(student_days_present), round(student_days_absent)) ~ data_schoolyear,
   data = read_rds(nested_here("data", "analytic_school_lvl.rds")) |> 
     filter(!is.na(student_count)) |> 
     droplevels(),
   family = binomial(link = "logit"),
   id     = school_id,
   waves  = data_schoolyear
   )
```






Schools that appear in inhaler events but not in CPS data extract (charter and 
contrast schools):

```{r}
cps_sy25 <- fetch_from_box(list(box_id = "2155107786545", sheet = "Schools"))

# tabulate annual school-level summaries
read_rds(nested_here("data", "mrg_inhaler_events.rds")) |> 
  anti_join(
       read_rds(nested_here("data", "mrg_student_counts.rds")) |> 
        distinct(school_id)
       ) |> 
  count(school_id, school_match_name, data_schoolyear) |> 
  
  left_join(
    janitor::clean_names(set_names(cps_sy25[2:nrow(cps_sy25),], cps_sy25[1,])),
    by  = "school_id"
    )
```

```{r}
right_join(
  read_rds(nested_here("data", "mrg_inhaler_events.rds")) |> 
    summarise(n_events = n(), .by = c(school_id, data_schoolyear)),
  read_rds(nested_here("data", "mrg_student_counts.rds")) |> 
    distinct(school_id),
  by = "school_id"
  ) |> 
  complete(school_id, data_schoolyear, fill = list(n_events = 0)) |> 
  filter(!is.na(data_schoolyear)) |> 
  
  arrange(school_id, data_schoolyear) |> 
  mutate(
    n_events_cumulative = cumsum(n_events), 
    
    across(starts_with("n_events"), list(
      any = ~ I(.x > 0),
      ord = ~ cut(
        .x, 
        breaks = c(-Inf, 0, 1, Inf), 
        labels = c("0", "1", "2+"),
        include.lowest = TRUE
        )
      )),
    .by = school_id
    )
```



```{r}
library(arsenal) 
tableby(
  ~ .,
  data = read_rds(nested_here("data", "mrg_inhaler_events.rds")) |> 
    select(-matches(" "), -school_match_name, -school_id)
  ) |> 
  summary()
```



- [x] Read data from Box. Raw files:

```{r}
params |> 
  keep_at(~ grepl("raw_data", .x)) |> 
  map_dfr(as.list, .id = "contents") |> 
  knitr::kable()
```
